name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  audit:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Tap local repository
        run: brew tap kimulaco/term-survivors "$GITHUB_WORKSPACE"
      - name: Audit formula
        run: brew audit --formula term-survivors
